[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 99
target_version = ['py38']
exclude = '''
(
          /pegen/grammar_parser.py            # generated file
        | /tests/python_parser/data/          # test files
        | /tests/python_parser/parser_cache/  # generated parser
)
'''
